config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
  get "about", to: "pages#about"

  resources :owners
  resources :dogs
  resources :breeds
  resources :sub_breeds
  resources :traits
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :sub_breeds, only: [] do
    collection do
      get :by_breed
    end
  end

end

app/models/sub_breed.rb
class SubBreed < ApplicationRecord
  belongs_to :breed
  has_many :dogs, dependent: :destroy
  has_many :images, dependent: :destroy
end

app/controllers/sub_breeds_controller.rb
class SubBreedsController < ApplicationController
  before_action :set_sub_breed, only: %i[ show edit update destroy ]

  # GET /sub_breeds or /sub_breeds.json
  def index
    @sub_breeds = SubBreed.all
  end

  # GET /sub_breeds/1 or /sub_breeds/1.json
  def show
  end

  # GET /sub_breeds/new
  def new
    @sub_breed = SubBreed.new
  end

  # GET /sub_breeds/1/edit
  def edit
  end

  def by_breed
    sub_breeds = SubBreed.where(breed_id: params[:breed_id])
    render json: sub_breeds
  end

  # POST /sub_breeds or /sub_breeds.json
  def create
    @sub_breed = SubBreed.new(sub_breed_params)

    respond_to do |format|
      if @sub_breed.save
        format.html { redirect_to @sub_breed, notice: "Sub breed was successfully created." }
        format.json { render :show, status: :created, location: @sub_breed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_breeds/1 or /sub_breeds/1.json
  def update
    respond_to do |format|
      if @sub_breed.update(sub_breed_params)
        format.html { redirect_to @sub_breed, notice: "Sub breed was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @sub_breed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_breeds/1 or /sub_breeds/1.json
  def destroy
    @sub_breed.destroy!

    respond_to do |format|
      format.html { redirect_to sub_breeds_path, notice: "Sub breed was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_breed
      @sub_breed = SubBreed.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def sub_breed_params
      params.expect(sub_breed: [ :name, :breed_id ])
    end
end

app/helpers/sub_breeds_helper.rb
module SubBreedsHelper
end

app/views/sub_breeds/_form.html.erb
<%= form_with(model: sub_breed) do |form| %>
  <% if sub_breed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sub_breed.errors.count, "error") %> prohibited this sub_breed from being saved:</h2>

      <ul>
        <% sub_breed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :breed_id, style: "display: block" %>
    <%= form.text_field :breed_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_breeds/_sub_breed.html.erb
<div id="<%= dom_id sub_breed %>">
  <p>
    <strong>Name:</strong>
    <%= sub_breed.name %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= sub_breed.breed_id %>
  </p>

</div>

app/views/sub_breeds/edit.html.erb
<% content_for :title, "Editing sub breed" %>

<h1>Editing sub breed</h1>

<%= render "form", sub_breed: @sub_breed %>

<br>

<div>
  <%= link_to "Show this sub breed", @sub_breed %> |
  <%= link_to "Back to sub breeds", sub_breeds_path %>
</div>

app/views/sub_breeds/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Sub breeds" %>

<h1>Sub breeds</h1>

<div id="sub_breeds">
  <% @sub_breeds.each do |sub_breed| %>
    <%= render sub_breed %>
    <p>
      <%= link_to "Show this sub breed", sub_breed %>
    </p>
  <% end %>
</div>

<%= link_to "New sub breed", new_sub_breed_path %>

app/views/sub_breeds/new.html.erb
<% content_for :title, "New sub breed" %>

<h1>New sub breed</h1>

<%= render "form", sub_breed: @sub_breed %>

<br>

<div>
  <%= link_to "Back to sub breeds", sub_breeds_path %>
</div>

app/views/sub_breeds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sub_breed %>

<div>
  <%= link_to "Edit this sub breed", edit_sub_breed_path(@sub_breed) %> |
  <%= link_to "Back to sub breeds", sub_breeds_path %>

  <%= button_to "Destroy this sub breed", @sub_breed, method: :delete %>
</div>